@startuml
'skinparam monochrome true
queue Kafka

group VehicleBlock
    hide unlinked
    autonumber
    User -> Controller: Blocks a partially available vehicle
    Controller-> BlockVehicleService: Performs validation
    BlockVehicleService-> VehicleBlockStrategy: Decide if provisional blocking required
    VehicleBlockStrategy-> VehicleBlocking: Block vehicle, \nUpdate vehicle in RA, \nUnblock if required, \nUpdate blocked vehicle cache with \nvehicle block type
    VehicleBlocking -> User: Return or throw exception
end
@enduml