@startuml

'skinparam monochrome true

queue Kafka

group ProvisionalBlock
    hide unlinked
    autonumber
    User ->DC: Select a partially available vehicle
    DC-> VA_PB: Block vehicle provisionally
    VA_PB-> VA_PB: Internal queue
    User-> DC: Make payment
    DC-> RA: RA_Payment with payment details ( skip updating VA-> RENTED)

    VA_PB-> Kafka: Vehicle is available now (Vehicle marked is TH)
    Kafka-> DC: PA event saying vehicle is TH - do operation as needed
    DC-> DC: Make it vehicle rented
end
@enduml