@startuml
'https://plantuml.com/sequence-diagram
!include <logos/slack>

autonumber
group rentalAgreementGenerator
    PaymentHandlerService -> RentalAgreementGeneratorService: If payment authorisation is successful place a request
    RentalAgreementGeneratorService -> RentalAgreementGeneratorService: Get rental-activity and raDomain Object from dcDomain Object
    RentalAgreementGeneratorService->BookingUtils: getKeyboxDetailsOfVehicle request
    RentalAgreementGeneratorService<-BookingUtils: KeyboxDetailsDomainObject as response
    alt KeyboxDetailsDomainObject is null
         RentalAgreementGeneratorService->PaymentHandlerService: return false
    else KeyboxDetailsDomainObject has keyIn feild
        RentalAgreementGeneratorService->RentalActivityServiceClient:  update rental-activity with Action INITIATE_RENTAL_AGREEMENT_WRITE_BACK
    alt Success scenario
        RentalActivityServiceClient->ObservabilityService:notify recordTime
        RentalActivityServiceClient->DcDomainEnrichService: enrichDcDomain with new rental-activity details
        RentalActivityServiceClient->RentalAgreementGeneratorService: return rental-activity response
    else failure scenario
        RentalActivityServiceClient->RentalAgreementGeneratorService:RpcCallException
        RentalActivityServiceClient->ObservabilityService: notify callToClientConfigFailed
    end
        RentalAgreementGeneratorService->DcDomainEnrichService: enrichDcDomain with updated details
        RentalAgreementGeneratorService->RentalActivityServiceClient:rentalWriteback async request
        RentalAgreementGeneratorService->PaymentHandlerService: return true
    else Ra_status is not RA_PAYMENT
        participant "<$slack>" as AlertService
        RentalAgreementGeneratorService->AlertService: send slack alert saying RA_Status isnt RA_PAYMENT
        RentalAgreementGeneratorService->PaymentHandlerService: return false
    else Exception is caught
        RentalAgreementGeneratorService->AlertService: send slack alert saying error
        RentalAgreementGeneratorService->ObservabilityService: notify dcServiceExceptions
        RentalAgreementGeneratorService->PaymentHandlerService: return false
    end
end
@enduml